import {creativePreflight} from "./creative-engine.js";
const req=["researchRef","opportunityTheme","creativeConcept","visualMotif","productType","blueprintId","providerId","variantId","economics"];
export function lockArtworkChain(x={}){
 const missing=req.filter(k=>x[k]==null||x[k]==="");const econ=x.economics||{},theme=String(x.opportunityTheme||"").trim(),concept=String(x.creativeConcept||"").trim();
 const blockers=[...missing.map(k=>k.toUpperCase()+"_MISSING")];
 if(econ.approved!==true)blockers.push("ECONOMICS_NOT_APPROVED");
 if(theme&&!concept.toLowerCase().includes(theme.toLowerCase()))blockers.push("CONCEPT_THEME_MISMATCH");
 const ip=creativePreflight({theme,concept});if(!ip.ok)blockers.push("IP_HOLD");
 if(blockers.length)return {status:"ARTWORK_BLOCKED",approved:false,blockers};
 const motif=String(x.visualMotif||"").trim();if(motif.length<40)return {status:"ARTWORK_BLOCKED",approved:false,blockers:["VISUAL_MOTIF_INCOMPLETE"]};\n const locked={researchRef:x.researchRef,opportunityTheme:theme,creativeConcept:concept,visualMotif:motif,productType:x.productType,blueprintId:Number(x.blueprintId),providerId:Number(x.providerId),variantId:Number(x.variantId),economics:{approved:true,marginPct:econ.marginPct},forbiddenThemes:x.forbiddenThemes||[]};
 return {status:"ARTWORK_CHAIN_LOCKED",approved:true,blockers:[],locked,artworkPrompt:`Create ONLY the final printable artwork for a ${locked.productType}. Locked researched theme: "${theme}". Locked creative concept: "${concept}". Exact visual motif/composition: "${motif}". Generate the flat standalone print artwork itself, edge-to-edge on a plain canvas. Do not show the artwork hanging, framed, photographed, held, displayed in a room, or applied to any product. Do not introduce anything outside the locked researched theme, creative concept and visual motif. No mockup, frame, room scene, packaging, size chart, ecommerce layout or sales callouts. Original composition only; no third-party logos/characters. If the requested image cannot faithfully follow this locked chain, do not generate it.`};
}
export function validateArtworkRequest(lock={},prompt=""){if(lock.status!=="ARTWORK_CHAIN_LOCKED")return {ok:false,status:"ARTWORK_BLOCKED",blockers:["CHAIN_NOT_LOCKED"]};const p=String(prompt).toLowerCase(),t=String(lock.locked?.opportunityTheme||"").toLowerCase();const bad=(lock.locked?.forbiddenThemes||[]).filter(x=>p.includes(String(x).toLowerCase()));return {ok:!!t&&p.includes(t)&&!bad.length,status:!!t&&p.includes(t)&&!bad.length?"ARTWORK_REQUEST_VALID":"ARTWORK_BLOCKED",blockers:bad.length?bad.map(x=>"FORBIDDEN_THEME_"+String(x).toUpperCase().replace(/\W+/g,"_")):["LOCKED_THEME_NOT_PRESENT"].filter(()=>!p.includes(t))};}
