const banned=["disney","marvel","star wars","pokemon","harry potter","nike","adidas"];
const modes=["illustrative editorial","surreal graphic","bold typographic","retro print","maximalist decorative","minimal art","character-free visual humor","folk-inspired geometric","collage-like abstract","playful pattern","premium monoline","unexpected object study"];
const visualByTheme={
 "curated gallery wall":["an impossible museum specimen: a porcelain teacup cracked open like a geode, revealing a tiny glowing midnight-blue star field inside; one delicate botanical sprig grows from the cosmic fracture while its shadow forms a perfect doorway; warm ivory ground, terracotta and cobalt accents; surreal focal object, no text, no scenery, no landmarks","a sculptural ceramic vase whose painted cobalt pattern physically peels away from the vessel as folded paper birds, leaving precise blank silhouettes behind; one terracotta circle becomes a rising sun only inside the vase's shadow; restrained ivory ground, editorial print texture; no text, no scenery, no landmarks","an elegant impossible still-life where three stacked ceramic vessels share one continuous botanical stem that passes through solid surfaces and changes from leaf to cut-paper to ink line at each boundary; bold negative space, ivory, terracotta, cobalt and charcoal; no text, no scenery, no landmarks"],
 "nostalgic gallery prints":["an impossible archival object study: a vintage rotary telephone whose coiled cord transforms continuously into a hand-drawn maze and then into a blooming flower, composed as one graphic museum-catalogue specimen; faded cream, oxblood, ink blue; no brands, no text, no scenery","a surreal collection of familiar analog objects nested inside one another like impossible memory boxes: cassette shell, matchbook form and alarm-clock silhouette, with one continuous red thread connecting every layer; tactile retro print texture; no logos, no text, no scenery"],
 "whimsical polka dots":["an impossible polka-dot system designed for a phone case: oversized glossy dots behave like physical portals, each revealing a smaller offset dot beneath it, while three dots stretch into liquid droplets that weave around the camera-safe upper corner; punchy cream, tomato red, cobalt blue and butter yellow, strong edge-to-edge rhythm, no text, no brands, no scenery","a playful optical illusion made entirely from polka dots: orderly rows begin as flat circles, then several dots peel upward like curled paper discs and cast crisp graphic shadows while one trail of tiny dots loops between them; cream ground with cherry red, cobalt and warm yellow, bold vertical phone-case composition, no text, no brands, no scenery","a surreal dot cascade built for a slim phone case: large colored circles appear to pass through one another like interlocking rings, changing scale from bottom to top and bending around a reserved camera zone; saturated red, blue, apricot and cream, tactile screen-print texture, no text, no brands, no scenery"],
 "small everyday celebration":["a deadpan visual celebration: an ordinary grocery receipt shape erupts into an extravagant paper-cut firework while a tiny coffee cup casts the shadow of a trophy; crisp editorial composition, playful scale contrast, no brands, no readable text","a tiny mundane desk object presented as a monumental award ceremony: bent paperclip on a velvet-like plinth with absurdly grand radiating cut-paper fanfare and confetti frozen into geometric orbit; visual humor through scale and juxtaposition; no text, no brands"]
};
function visualConcept(theme,mode,seed){const set=visualByTheme[theme];if(set?.length)return set[Math.abs(Number(seed)||0)%set.length];return null;}
export function creativeBrief(o={},seed=0){const mode=modes[Math.abs(Number(seed)||0)%modes.length],visualMotif=visualConcept(o.theme,mode,seed);return {candidateKey:o.candidateKey||null,theme:o.theme,audience:o.audience,occasion:o.occasion||"evergreen",creativeDirection:mode,visualMotif,requirements:["original composition","commercially distinctive","no third-party logos or characters","production-safe artwork","final artwork only; never a mockup or room scene"],conceptPrompt:visualMotif?`Create an original ${mode} artwork for ${o.audience||"a defined audience"} around ${o.theme||"the researched opportunity"}. Exact visual composition: ${visualMotif}. Do not imitate marketplace artwork.`:null};}
export function exploreConcepts(o={},count=8){return Array.from({length:Math.max(1,count)},(_,i)=>creativeBrief(o,i));}
export function scoreConcept(c={},signals={}){const keys=["researchFit","originality","visualImpact","productBreadth","productionFit","ipSafety","distinctiveness","hookStrength"],missing=keys.filter(k=>!Number.isFinite(Number(signals[k])));if(missing.length)return {score:null,approved:false,status:"CREATIVE_EVIDENCE_INCOMPLETE",blockers:missing.map(k=>`${k.toUpperCase()}_MISSING`)};const s=Object.fromEntries(keys.map(k=>[k,Number(signals[k])]));const score=Math.round((s.researchFit*.20+s.originality*.16+s.visualImpact*.14+s.productBreadth*.08+s.productionFit*.10+s.ipSafety*.10+s.distinctiveness*.12+s.hookStrength*.10)*10)/10;return {...s,score,approved:score>=65&&s.distinctiveness>=70&&s.hookStrength>=70,status:score>=65&&s.distinctiveness>=70&&s.hookStrength>=70?"CREATIVE_APPROVED":"CREATIVE_REJECT",blockers:score>=65&&s.distinctiveness>=70&&s.hookStrength>=70?[]:[...(score<65?["CREATIVE_SCORE_BELOW_FLOOR"]:[]),...(s.distinctiveness<70?["DISTINCTIVENESS_BELOW_FLOOR"]:[]),...(s.hookStrength<70?["HOOK_STRENGTH_BELOW_FLOOR"]:[])]};}
export function selectConcepts(concepts=[],signalFn=()=>({}),limit=3){return concepts.map((c,i)=>({...c,creativeScore:scoreConcept(c,signalFn(c,i))})).filter(x=>x.creativeScore.approved&&creativePreflight(x).ok&&String(x.visualMotif||"").length>=120&&String(x.conceptPrompt||"").length>=160).sort((a,b)=>b.creativeScore.score-a.creativeScore.score).slice(0,limit);}
export function matchProducts(concept={},products=[]){return products.map(p=>{const evidence=Number(p.researchEvidence??0),fit=Number(p.designFit??0),score=Math.round((evidence*.56+fit*.44)*10)/10;return {...p,matchScore:score,concept:concept.creativeDirection}}).filter(x=>x.researchEvidence>=50&&x.matchScore>=60).sort((a,b)=>b.matchScore-a.matchScore);}
export function creativePreflight(b={}){const t=JSON.stringify(b).toLowerCase();const hits=banned.filter(x=>t.includes(x));return {ok:hits.length===0,hits,status:hits.length?"IP_HOLD":"CREATIVE_READY"}}
